import Head from "next/head"
import Link from "next/link"

import fm, { FrontMatterResult } from "front-matter"
import { readdirSync, readFileSync } from "fs"
import Markdown from 'markdown-to-jsx'

export default function Home({ posts }) {
	return (
		<>
			<Head>
				<title>V1B3</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="mx-5 my-10">
				<h2 className="mb-5 text-xl">Posts</h2>
				<ul className="">
					{posts.map(({ date, slug, title, categories }) => {
						return (
							<li key={slug} className="flex items-baseline gap-5">
								<time className="text-xs text-center uppercase">
									{date}
								</time>
								<div>
									<h3 className="text-3xl underline hover:text-red-600">
										<Link href={`/posts/${slug}`}>
											<Markdown>{title}</Markdown>
										</Link>
									</h3>
									<ul>
										{categories?.map((category) => (
											<li key={category} className="text-xs">
												{category}
											</li>
										))}
									</ul>
								</div>
							</li>
						)
					})}
				</ul>
			</main>
		</>
	)
}

type PostAttributes = {
	date: string
	title: string
	categories?: string
}

export async function getStaticProps() {
	const rootDir = process.cwd() + "/content"
	const posts = readdirSync(rootDir)
		.map((file) => {
			return {
				slug: file.replace(".md", ""),
				...fm(readFileSync(rootDir + "/" + file, "utf8").toString()),
			}
		})
		.map((post: { slug: string } & FrontMatterResult<PostAttributes>) => ({
			slug: post.slug,
			date: new Date(post.attributes.date).toLocaleString("en-US", {
				month: "short",
				day: "2-digit",
				year: "numeric",
			}),
			title: post.attributes.title.replace(/\\`/gim, "`"),
			categories: post.attributes.categories?.split(", "),
		}))
	return {
		props: {
			posts,
		},
	}
}
